### ISSUE TITLE
stream[field]?.toLowerCase is not a function

### ISSUE THREAD

**Issue by Arjailer** [varthe/Defaulterr#11]
Getting lots of these errors when doing a dry run on my movie library - it might even be on every file as I'm not seeing any successful messages

`2024-10-12T19:12:51.665Z [error]: Error while evaluating streams for filter: stream[field]?.toLowerCase is not a function. Aborting`

My setup is currently pretty simple as I'm just getting started:

```
groups:
  everyone:
    - $ALL

filters:
  Films:
    everyone:
      audio:
        # first stereo track by default
        - include:
            channels: 2
        # fallback to any english track if stereo not available
        - include:
            language: English
```

I'm assuming `channels` is valid as it appears in the `example.json` in the repo, but I might be wrong
