### ISSUE TITLE
Error fetching users from server: No response received.

### ISSUE THREAD

**Issue by amadejvidic** [varthe/Defaulterr#22]
Hi, I'm using my Plex server as a single user (I guess this means owner?) and I don't have Plex Pass. When starting the container I get the following error:

`
2024-10-19T13:10:08.319Z [info]: YAML file is valid according to the schema.
2024-10-19T13:10:08.327Z [info]: Server is running on port 3184
2024-10-19T13:10:13.393Z [error]: Error fetching users from server: No response received.
`

This is my config.yaml file:

```

# REQUIRED
plex_server_url: "http://x.x.x.x:32400"
plex_owner_name: "owner" # Use this value in place of username to include the owner in groups
plex_owner_token: "xxxxx"
plex_client_identifier: "xxxxx" # See README on how to obtain
# REQUIRED END

# RUN SETTINGS
dry_run: True # For testing filters; won't update users. Recommended to test a few times to ensure filters work.

# PARTIAL RUN: Updates newly added media since the last run.
# WARNING: The first run will update all existing media. Subsequent runs will be faster.
partial_run_on_start: False
partial_run_cron_expression: "" # E.g., '0 3 * * *' to run every day at 3:00 am. See crontab.guru
# RUN SETTINGS END

# GROUPS
groups:
  allUsers:
    - owner
# GROUPS END

# FILTERS - See README for explanation
filters:
  Movies:
    allUsers:
      audio:
        - include:
            language: English # Needs to be in the original language, e.g Español for Spanish
            # languageCode: eng # Alternative to the above, e.g. jpn for Japanese
          exclude:
            codec: truehd
            extendedDisplayTitle: commentary
        - include:
            language: English
```

**Comment by varthe** [comment]
Hi it's trying to grab users with access to your server, which there aren't any. I'll push out a fix in a bit

**Comment by amadejvidic** [comment]
Hi @varthe, I just tested it and it's working now 🙂 But I have another question. Does the code support listing multiple codecs under exclude such as the following: 

```
filters:
  Movies:
    allUsers:
      audio:
        - include:
            language: English  # Needs to be in the original language, e.g Español for Spanish
            # languageCode: eng # Alternative to the above, e.g. jpn for Japanese
          exclude:
            codec: 
              - truehd
              - dca
              - dca-ma
            extendedDisplayTitle: commentary
```

I'm trying to exclude TRUE HD, DTS, DTS HD-MA but it's not working, maybe this codec key does not support a list?
