### ISSUE TITLE
Taululli Webhook Library ID not found

### ISSUE THREAD

**Issue by eric9876-git** [varthe/Defaulterr#41]
Hi!  I am loving this tool so thank you for making it.

I am having an issue with Taululli Webhook.  It's configured as instructed.  I see the webhook received by defaulterr in the log but I get a log entry saying the Library ID is not found.   

**Log Message:**
2025-02-08 18:41:25 [INFO]: Tautulli webhook received. Processing...
2025-02-08 18:41:25 [INFO]: Library ID 2 not found in filters. Ending request

**Tautulli Webhook Config / Recently Added JSON Data:**

```
<movie>
{
  "type": "movie",
  "libraryId": "{section_id}",
  "mediaId": "{rating_key}"
}
</movie>

<show>
{
  "type": "show",
  "libraryId": "{section_id}",
  "mediaId": "{rating_key}"
}
</show>

<season>
{
  "type": "season",
  "libraryId": "{section_id}",
  "mediaId": "{rating_key}"
}
</season>

<episode>
{
  "type": "episode",
  "libraryId": "{section_id}",
  "mediaId": "{rating_key}"
}
</episode>
```

**Config.yaml:**

This particular show was downloaded to Plex Library "TV Kiki".  This is the filter section for that library:

```
TV KiKi:
    aacandsubs:
      audio:
        - include:
            codec:
              - aac
        - exclude:
            codec:
              - ac3
              - dts
              - truehd
      subtitles:
        - include:
            language: English
    aaconly:
      audio:
        - include:
            codec:
              - aac
        - exclude:
            codec:
              - ac3
              - dts
              - truehd
    surroundnosubs:
      audio:
        - include:
            language: English
            codec:
             - ac3
             - truehd
          on_match:
            subtitles: disabled
        - include:
            language: English
          on_match:
            subtitles: disabled

```
**Sidebar question:** is there any way I can set the Time Zone in the container, via the docker-compose file using an environment variable?  It's tough to troubleshoot issues such as the one above when the timestamps don't line up.  Also for the CRON job :)

**Comment by varthe** [comment]
> **Log Message:** 2025-02-08 18:41:25 [INFO]: Tautulli webhook received. Processing... 2025-02-08 18:41:25 [INFO]: Library ID 2 not found in filters. Ending request

Library name in the config is probably wrong. If it's `TV Kiki` in plex it should be exactly `TV Kiki` in the config.

> is there any way I can set the Time Zone in the container

You can set it in the compose like this:
```yaml
services:
  defaulterr:
    image: varthe/defaulterr:latest
    container_name: defaulterr
    hostname: defaulterr
    ports:
      - 3184:3184
    volumes:
      - /path/to/config:/config
      - /path/to/logs:/logs
    environment:
      - TZ=Europe/London # <-- Timezone here
      - LOG_LEVEL=info
```
Here is a list of valid timezones:
[https://en.wikipedia.org/wiki/List_of_tz_database_time_zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
